service: atcoder-notifier

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: provided.al2
  stage: prod
  region: ap-northeast-1

package: 
  artifact: .build/lambda/lambda.zip

functions:
  notify:
    handler: Notifier
    memorySize: 128
    events:
      - schedule: cron(0 23 ? * 1 *)
    environment:
      SLACK_URL: ${env:SLACK_URL}
