service: atcoder-notifier

frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-swift

provider:
  name: aws
  runtime: swift
  stage: prod
  region: ap-northeast-1

functions:
  notify:
    handler: ./Notifier
    memorySize: 128
    events:
      - schedule: cron(0 23 * * ? *)
    environment:
      SLACK_URL: ${env:SLACK_URL}
