service: atcoder-notifier

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: provided.al2
  stage: prod
  region: ap-northeast-1

functions:
  notify:
    handler: .build/release/Notifier
    memorySize: 128
    events:
      - schedule: cron(0 23 * * MON *)
    environment:
      SLACK_URL: ${env:SLACK_URL}
